apiVersion: v1
kind: Service
metadata:
  name: clinic-app-service
  labels:
    app: clinic-app
    tier: frontend
spec:
  type: LoadBalancer # Or NodePort, depending on how you want to expose it
  ports:
    - port: 80
      targetPort: 80 # Matches containerPort in clinic-app-deployment
      # nodePort: 30080 # If using NodePort, specify a port (optional)
  selector:
    app: clinic-app
    tier: frontend

