apiVersion: v1
kind: Service
metadata:
  name: mysql-clinic-service
  labels:
    app: mysql-clinic
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-clinic
    tier: database
  # type: ClusterIP # Default, suitable for internal communication

